"""
MOS Evaluation Study — Speech Synthesis
Master Project: Dialogue Speech Generation
"""

import streamlit as st
import pandas as pd
import os
import random
import hashlib
from datetime import datetime
from pathlib import Path

# ─────────────────────────────────────────────
# CONFIGURATION — Edit this section to update stimuli
# ─────────────────────────────────────────────

# Audio file paths — place your files accordingly
# Structure: audio/en/model_1/clip.wav, audio/en/model_2/clip.wav, ...
# Ground truth for EN: audio/en/ground_truth/clip.wav

EN_STIMULI = [
    {"id": "en_gt",      "label": "EN-GT",  "path": "audio/en/ground_truth/clip.wav"},
    {"id": "en_m1",      "label": "EN-M1",  "path": "audio/en/model_1/clip.wav"},
    {"id": "en_m2",      "label": "EN-M2",  "path": "audio/en/model_2/clip.wav"},
    {"id": "en_m3",      "label": "EN-M3",  "path": "audio/en/model_3/clip.wav"},
    {"id": "en_m4",      "label": "EN-M4",  "path": "audio/en/model_4/clip.wav"},
    {"id": "en_m5",      "label": "EN-M5",  "path": "audio/en/model_5/clip.wav"},
    {"id": "en_m6",      "label": "EN-M6",  "path": "audio/en/model_6/clip.wav"},
    {"id": "en_m7",      "label": "EN-M7",  "path": "audio/en/model_7/clip.wav"},
]

DE_STIMULI = [
    {"id": "de_m1",      "label": "DE-M1",  "path": "audio/de/model_1/clip.wav"},
    {"id": "de_m2",      "label": "DE-M2",  "path": "audio/de/model_2/clip.wav"},
    {"id": "de_m3",      "label": "DE-M3",  "path": "audio/de/model_3/clip.wav"},
    {"id": "de_m4",      "label": "DE-M4",  "path": "audio/de/model_4/clip.wav"},
    {"id": "de_m5",      "label": "DE-M5",  "path": "audio/de/model_5/clip.wav"},
    {"id": "de_m6",      "label": "DE-M6",  "path": "audio/de/model_6/clip.wav"},
    {"id": "de_m7",      "label": "DE-M7",  "path": "audio/de/model_7/clip.wav"},
]

# Practice audio (should NOT be from main stimuli)
PRACTICE_STIMULI = [
    {"id": "practice_1", "label": "Practice 1", "path": "audio/practice/practice_1.wav"},
]

# Output directory for results
RESULTS_DIR = "results"
os.makedirs(RESULTS_DIR, exist_ok=True)

# Likert scale labels
LIKERT_OPTIONS = {
    1: "1 — Very poor",
    2: "2 — Poor",
    3: "3 — Fair",
    4: "4 — Good",
    5: "5 — Excellent",
}

DIMENSIONS = [
    {
        "key": "naturalness",
        "label": "Naturalness",
        "question": "How natural does the speech sound overall?",
        "anchors": ("Very unnatural", "Very natural"),
        "score_labels": {
            1: "Fully synthetic or robotic; extremely unnatural and monotone",
            2: "Noticeably synthetic; unnatural artifacts or limited prosodic variation",
            3: "Moderately natural; occasional synthetic artifacts or uneven prosody",
            4: "Largely natural with minor imperfections (e.g. slight flatness or over-emphasis)",
            5: "Completely natural; indistinguishable from a human recording",
        },
    },
    {
        "key": "intelligibility",
        "label": "Intelligibility",
        "question": "How easy was it to understand what was being said?",
        "anchors": ("Very hard to understand", "Perfectly clear"),
        "score_labels": {
            1: "Impossible to understand",
            2: "Difficult to understand; many words are unclear",
            3: "Most words are understandable; some effort required",
            4: "Almost all words are clear; minor effort occasionally required",
            5: "Every word is perfectly clear and understandable",
        },
    },

    {
        "key": "emotional_appropriateness",
        "label": "Emotional Appropriateness",
        "question": "How appropriate are the emotions conveyed in the speech for the dialogue context? (e.g. a client talking about something bad that happened should not sound happy)",
        "anchors": ("Completely inappropriate", "Perfectly appropriate"),
        "score_labels": {
            1: "Completely inappropriate; emotion entirely mismatches with the context",
            2: "Mostly inappropriate",
            3: "Moderately appropriate",
            4: "Largely appropriate",
            5: "Completely appropriate; emotion perfectly matches the dialogue context",
        },
    },
    {
        "key": "human_or_ai",
        "label": "Human or AI",
        "question": "Does this speech sound like it was produced by a human or generated by AI?",
        "type": "categorical",
        "options": ["Human", "Unsure", "AI"],
    },
]


# ─────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────

def get_results_path(participant_id: str) -> str:
    safe_id = "".join(c for c in participant_id if c.isalnum() or c in "_-")
    return os.path.join(RESULTS_DIR, f"participant_{safe_id}.csv")


def save_rating(participant_id: str, block: str, stimulus_id: str,
                stimulus_label: str, position: int, ratings: dict,
                demographics: dict):
    """Append a single stimulus rating to the participant's CSV."""
    row = {
        "timestamp": datetime.now().isoformat(),
        "participant_id": participant_id,
        "block": block,
        "stimulus_id": stimulus_id,
        "stimulus_label": stimulus_label,
        "position_in_block": position,
        **{f"rating_{k}": v for k, v in ratings.items()},
        **{f"demo_{k}": v for k, v in demographics.items()},
    }
    path = get_results_path(participant_id)
    df_new = pd.DataFrame([row])
    df_combined = df_new
    if os.path.exists(path) and os.path.getsize(path) > 0:
        try:
            df_existing = pd.read_csv(path)
            df_combined = pd.concat([df_existing, df_new], ignore_index=True)
        except (pd.errors.EmptyDataError, pd.errors.ParserError):
            pass  # File is unreadable; overwrite with the new row.
    df_combined.to_csv(path, index=False)


def save_comment(participant_id: str, comment: str):
    path = os.path.join(RESULTS_DIR, "comments.csv")
    row = {
        "timestamp": datetime.now().isoformat(),
        "participant_id": participant_id,
        "comment": comment,
    }
    df_new = pd.DataFrame([row])
    df_combined = df_new
    if os.path.exists(path) and os.path.getsize(path) > 0:
        try:
            df_existing = pd.read_csv(path)
            df_combined = pd.concat([df_existing, df_new], ignore_index=True)
        except (pd.errors.EmptyDataError, pd.errors.ParserError):
            pass
    df_combined.to_csv(path, index=False)


def deterministic_shuffle(items: list, seed: str) -> list:
    """Shuffle a list deterministically based on a seed string."""
    items = items.copy()
    h = int(hashlib.md5(seed.encode()).hexdigest(), 16)
    rng = random.Random(h)
    rng.shuffle(items)
    return items


def init_session():
    """Initialise all session state keys that don't exist yet."""
    defaults = {
        "page": "welcome",
        "participant_id": "",
        "demographics": {},
        "language_order": ["en", "de"],
        "en_order": list(range(len(EN_STIMULI))),
        "de_order": list(range(len(DE_STIMULI))),
        "practice_index": 0,
        "block": "en",           # current block
        "stimulus_index": 0,     # position within current block
        "listened": False,
        "current_ratings": {},
        "completed_blocks": [],
        "comment_saved": False,
    }
    for k, v in defaults.items():
        if k not in st.session_state:
            st.session_state[k] = v


def go_to(page: str):
    st.session_state.page = page
    st.session_state.listened = False
    st.session_state.current_ratings = {}
    st.rerun()


def progress_bar(current: int, total: int, label: str = ""):
    fraction = current / total if total > 0 else 0
    st.progress(fraction, text=f"{label}  {current} / {total}")


# ─────────────────────────────────────────────
# PAGE FUNCTIONS
# ─────────────────────────────────────────────

def page_welcome():
    st.title("Evaluating properties of AI-generated therapeutic speech")

    st.markdown("""
    ### Welcome and thank you for participating!

    This study is part of a Master Thesis project at the **Technische Universität Darmstadt**.

    - **Master Thesis student:** Marleen Sinsel
    - **Supervisors:** Dr. Simone Balloccu, Doan Nam Long Vu
    - **Contact:** marleen.sinsel@stud.tu-darmstadt.de

    You will be asked to listen to a series of audio excerpts of therapeutic conversations
    and rate them on several perceptual dimensions. These audio clips may come from real human speakers or AI speech synthesis systems.

    **What to expect:**
    - The study consists of two parts (English and German) and takes approximately **?? minutes** in total.
    - Please use **headphones** for the best listening experience.
    - Please conduct the study on a laptop or desktop computer in a quiet environment, not on a mobile phone.
    """)

    st.divider()

    st.markdown("""
    ### Information Sheet & Privacy Statement

    **Subject of the study**  
    This study investigates how humans perceive speech from AI speech synthesis systems and real human speakers in the context of therapeutic conversations, by rating audio excerpts on various perceptual dimensions.

    **Process of the study**  
    Participants will listen to a series of audio excerpts of therapeutic conversations and rate 
    each clip on several perceptual dimensions. The study consists of two parts (one with English 
    clips, one with German clips). Participants complete the study online via a web application and 
    are asked to use headphones in a quiet environment on a laptop or desktop computer.

    **Duration and compensation**  
    Participation in the study will require approximately ?? minutes. Participants will not receive 
    any kind of compensation.

    **Possible benefit of the study**  
    This study contributes to research on the perceptual quality of AI-generated speech in mental health. Results may inform the development of more natural and trustworthy 
    speech synthesis systems for therapeutic applications or training resources for therapeutic learners.

    **Experiences and risks associated with participation**  
    The participants of the study do not face any risks which are greater than risks they face in 
    general life.

    ---

    **Privacy Statement**

    Data processing in the context of this study is performed according to the privacy regulations 
    of the General Data Protection Regulation (GDPR) and the Privacy and Freedom of Information law 
    of the State of Hessen (HDSIG). All data will only be used for the purposes described in this 
    Information Sheet.

    In the context of this study, the following information will be collected:  
    Perceptual ratings of audio clips.
                
    Personal data collected are:  
    Age, gender, language proficiency, and whether the participant has experience with therapeutic conversations.

    **Confidentiality**  
    All data collected in the course of the study are naturally confidential and will only be used 
    in anonymized form. Demographic data such as age group or native language do not allow deducing 
    unambiguous information about your person. You will be asked at no point of the study to disclose 
    your name or other unambiguous information about yourself.

    **Data storage**  
    Collected data will be stored locally on the Master Thesis student's password-protected laptop. Data storage takes place in a form which does not allow 
    conclusions about your person, meaning that all data will be anonymized. Raw data will be deleted 
    by June 30, 2026. This declaration of consent will be stored separately from the collected data 
    and will be destroyed by the same date.

    **Voluntariness & Rights of the participants**  
    Your participation in this study is voluntary. You can withdraw from participation at any point 
    in time without facing any disadvantages. If you withdraw from participation, no data connected 
    to your person will be stored and already collected data will be deleted.  
    You have the right to request which data about your person have been stored and — if necessary — 
    demand that they are either corrected or deleted. You also have the right to restrict processing, 
    the right to object to processing and the right to data portability in a commonly used, structured 
    and machine-readable form.  
    In case of dissent you have the right to lodge a complaint with the Data Protection Officer of 
    Hessen: Email: Poststelle@datenschutz.hessen.de

    ---

    **Declaration of Consent**  
    I have read the explanations regarding the study and I hereby agree to participate.  
    I agree that any data collected in the course of the study will be analyzed for scientific 
    purposes and stored in anonymized form. I am aware that my participation is voluntary and that 
    I can withdraw at any time and without giving reasons.
    """)

    consent = st.checkbox("I confirm that I have read and understood the above information and agree to participate in this study.")

    st.divider()
    st.markdown("#### Please enter a participant code.")
    st.markdown("*Use a code you will remember (e.g. last two letters of mother's name + last two numbers of your telephone number. eg: KE00")

    pid = st.text_input("Participant code", max_chars=20,
                        placeholder="e.g. KE00",
                        value=st.session_state.participant_id)

    if st.button("Continue →", disabled=not consent or len(pid.strip()) < 3):
        st.session_state.participant_id = pid.strip().lower()

        # Determine language order: even hash → EN first, odd → DE first
        h = int(hashlib.md5(pid.encode()).hexdigest(), 16)
        if h % 2 == 0:
            st.session_state.language_order = ["en", "de"]
        else:
            st.session_state.language_order = ["de", "en"]

        # Shuffle stimuli deterministically per participant
        st.session_state.en_order = deterministic_shuffle(
            list(range(len(EN_STIMULI))), seed=pid + "_en")
        st.session_state.de_order = deterministic_shuffle(
            list(range(len(DE_STIMULI))), seed=pid + "_de")

        go_to("demographics")


def page_demographics():
    st.title("Background Information")
    st.markdown("Please answer the following questions about yourself.")
    st.divider()

    with st.form("demographics_form"):
        age = st.number_input("Age", min_value=18, max_value=99, step=1, value=None)

        gender = st.selectbox(
            "Gender",
            options=["", "Female", "Male", "Prefer not to say"],
        )

        st.markdown("##### Language proficiency")
        st.caption("Please rate your proficiency in the following languages.")

        english_level = st.selectbox(
            "English proficiency",
            options=["A1 (Beginner)", "A2", "B1", "B2", "C1", "C2 (Native/Near-native)"],
            index=3,
        )
        german_level = st.selectbox(
            "German proficiency",
            options=["A1 (Beginner)", "A2", "B1", "B2", "C1", "C2 (Native/Near-native)"],
            index=3,
        )

        st.markdown("##### Experience with therapeutic conversations")
        therapy_exp_receiving = st.radio(
            "How much experience do you have with **receiving** therapy (as a patient/client)?",
            options=[
                "None",
                "Some (one-time experience)",
                "Moderate (e.g. occasional therapy sessions)",
                "Extensive (e.g. ongoing or long-term therapy)",
            ],
            key="therapy_receiving",
        )
        therapy_exp_giving = st.radio(
            "How much experience do you have with **giving** therapy (as a therapist or student)?",
            options=[
                "None",
                "Some (e.g. a single practicum or role-play exercise)",
                "Moderate (e.g. coursework)",
                "Extensive (e.g. professional training or practicing therapist)",
            ],
            key="therapy_giving",
        )

        submitted = st.form_submit_button("Continue →")

    if submitted:
        if age is None or gender == "":
            st.error("Please fill in all fields.")
        else:
            st.session_state.demographics = {
                "age": age,
                "gender": gender,
                "english_level": english_level,
                "german_level": german_level,
                "therapy_experience_receiving": therapy_exp_receiving,
                "therapy_experience_giving": therapy_exp_giving,
            }
            go_to("instructions")


def page_instructions():
    st.title("Instructions")

    st.markdown("""
    You will listen to and rate parts of therapy conversations.
                
    **How each trial works:**
    1. An audio player will appear. Press play and listen to the full clip.
    2. Once you have listened, tick the checkbox to confirm.
    3. Rate the clip on all four dimensions.
    4. Press **Submit Rating** to move to the next clip.

    ---
                
    | Dimension | What you will rate |
    |---|---|
    | **Naturalness** | Does the speech sound like a real human talking, with natural variation in pitch, rhythm, and emphasis? |
    | **Intelligibility** | Can you clearly understand every word? |
    | **Emotional Appropriateness** | Do the emotions in the voice fit what is being said in the conversation? |
    | **Human or AI** | Does the speech sound like a human or AI? Choose: *Human*, *Unsure*, or *AI*. |


    """)

    st.warning(
        "Please evaluate the way the dialogue is spoken, not sentence structure, grammar or word choice. "
        "Focus on vocal characteristics such as naturalness, clarity, and fit to the situation."
        
    )
    st.warning(
        "Also: please listen to the **complete audio** before rating. You may replay it as many times as you like."
    )

    st.markdown("""
    ---

    **Structure of the study:**
    - First, you will complete a **practice trial** to get familiar with the task.
    - Then the main study begins in two blocks (English and German).
    - A short break screen will appear between blocks.
    """)

    if st.button("Start practice trials →"):
        st.session_state.practice_index = 0
        go_to("practice")


def page_practice():
    idx = st.session_state.practice_index
    total = len(PRACTICE_STIMULI)
    stimulus = PRACTICE_STIMULI[idx]

    st.title(f"Practice Trial {idx + 1} of {total}")
    st.info("This is a practice trial. Your ratings here will **not** be recorded.")
    progress_bar(idx, total, "Practice")
    st.divider()

    render_stimulus(stimulus, is_practice=True)

    if st.session_state.listened and len(st.session_state.current_ratings) == len(DIMENSIONS):
        if st.button("Next →" if idx < total - 1 else "Start main study →"):
            if idx < total - 1:
                st.session_state.practice_index += 1
                st.session_state.listened = False
                st.session_state.current_ratings = {}
                st.rerun()
            else:
                # Set first block
                st.session_state.block = st.session_state.language_order[0]
                st.session_state.stimulus_index = 0
                go_to("block_intro")


def page_block_intro():
    block = st.session_state.block
    lang_name = "English" if block == "en" else "German"
    total = len(EN_STIMULI) if block == "en" else len(DE_STIMULI)

    st.title(f"{lang_name} Block")
    st.markdown(f"""
    You are about to start the **{lang_name} block**.

    - This block contains **{total} audio clips**.
    - Rate each clip on the same four dimensions as in the practice trials.
    """)

    if st.button(f"Begin {lang_name} block →"):
        go_to("rating")


def page_rating():
    block = st.session_state.block
    order = st.session_state.en_order if block == "en" else st.session_state.de_order
    stimuli = EN_STIMULI if block == "en" else DE_STIMULI

    idx = st.session_state.stimulus_index
    total = len(order)
    stimulus = stimuli[order[idx]]

    lang_name = "English" if block == "en" else "German"

    st.title(f"{lang_name} Block — Clip {idx + 1}/{total}")
    progress_bar(idx, total, f"{lang_name} block")
    st.divider()

    render_stimulus(stimulus, is_practice=False)

    all_rated = len(st.session_state.current_ratings) == len(DIMENSIONS)

    if st.session_state.listened and all_rated:
        if st.button("Submit Rating →", type="primary"):
            # Save to CSV
            save_rating(
                participant_id=st.session_state.participant_id,
                block=block,
                stimulus_id=stimulus["id"],
                stimulus_label=stimulus["label"],
                position=idx,
                ratings=st.session_state.current_ratings,
                demographics=st.session_state.demographics,
            )

            # Advance
            if idx < total - 1:
                st.session_state.stimulus_index += 1
                st.session_state.listened = False
                st.session_state.current_ratings = {}
                st.rerun()
            else:
                # Block finished
                st.session_state.completed_blocks.append(block)
                remaining = [b for b in st.session_state.language_order
                             if b not in st.session_state.completed_blocks]
                if remaining:
                    st.session_state.block = remaining[0]
                    st.session_state.stimulus_index = 0
                    go_to("break")
                else:
                    go_to("thank_you")


def page_break():
    next_block = st.session_state.block
    lang_name = "English" if next_block == "en" else "German"
    st.title("Short Break")
    st.markdown(f"""
    Take a moment to rest before continuing with the **{lang_name} block**.

    When you feel ready, press the button below.
    """)

    if st.button(f"Continue to {lang_name} block →"):
        go_to("block_intro")


def page_thank_you():
    pid = st.session_state.participant_id
    st.title("Study concluded")
    st.success("Thank you for your participation!")
    st.markdown(f"""
    Your responses have been saved successfully under participant code **{pid}**.
    """)

    st.divider()
    st.markdown("#### Feedback(optional)")
    comment = st.text_area(
        "Feel free to share any feedback you have about this experiment",
        key="comment_input",
        disabled=st.session_state.comment_saved,
    )
    if not st.session_state.comment_saved:
        if st.button("Submit comment"):
            save_comment(pid, comment)
            st.session_state.comment_saved = True
            st.rerun()
    else:
        st.success("Comment saved!")

    st.markdown(" You may now close the window.")


# ─────────────────────────────────────────────
# SHARED STIMULUS RENDERING
# ─────────────────────────────────────────────

def _set_rating(dim_key: str, val):
    st.session_state.current_ratings[dim_key] = val


def render_stimulus(stimulus: dict, is_practice: bool):
    """Render the audio player and Likert rating form for one stimulus."""
    audio_path = stimulus["path"]
    st.markdown("#### Listen to the audio clip")
    st.caption("You may replay as many times as needed.")

    if os.path.exists(audio_path):
        with open(audio_path, "rb") as f:
            audio_bytes = f.read()
        st.audio(audio_bytes, format="audio/wav")
    else:
        st.warning(
            f"Audio file not found: `{audio_path}`\n\n"
            "*(Placeholder)*"
        )

    listened = st.checkbox(
        "✅ I have listened to the complete audio clip",
        value=st.session_state.listened,
        key=f"listened_{stimulus['id']}_{is_practice}",
    )
    st.session_state.listened = listened

    if not listened:
        st.info("Please listen to the full clip and tick the checkbox above before rating.")
        return

    st.divider()
    st.markdown("#### Rate the clip on the following dimensions")
    st.caption("1 = lowest, 5 = highest")

    for dim in DIMENSIONS:
        st.markdown(f"**{dim['label']}** — *{dim['question']}*")
        key = f"rating_{stimulus['id']}_{dim['key']}_{is_practice}"

        if dim.get("type") == "categorical":
            rating = st.radio(
                label=dim["label"],
                options=dim["options"],
                horizontal=True,
                index=None,
                label_visibility="collapsed",
                key=key,
            )
            if rating is not None:
                st.session_state.current_ratings[dim["key"]] = rating
        else:
            anchor_cols = st.columns(5)
            with anchor_cols[0]:
                st.caption(f"⬅ {dim['anchors'][0]}")
            with anchor_cols[4]:
                st.markdown(
                    f"<p style='text-align:right; font-size:0.8rem; color:grey; margin:0;'>{dim['anchors'][1]} ➡</p>",
                    unsafe_allow_html=True,
                )

            current_val = st.session_state.current_ratings.get(dim["key"])
            btn_cols = st.columns(5)
            for i, val in enumerate([1, 2, 3, 4, 5]):
                with btn_cols[i]:
                    st.button(
                        str(val),
                        key=f"{key}_{val}",
                        type="primary" if current_val == val else "secondary",
                        use_container_width=True,
                        on_click=_set_rating,
                        args=(dim["key"], val),
                    )

            score_labels = dim.get("score_labels")
            if score_labels:
                lbl_cols = st.columns(5)
                for i, val in enumerate([1, 2, 3, 4, 5]):
                    with lbl_cols[i]:
                        st.caption(score_labels[val])

        st.markdown("")  # spacing

    rated_count = len(st.session_state.current_ratings)
    if rated_count < len(DIMENSIONS):
        st.caption(f"*Please rate all dimensions ({rated_count}/{len(DIMENSIONS)} done)*")


# ─────────────────────────────────────────────
# MAIN ROUTER
# ─────────────────────────────────────────────

def main():
    st.set_page_config(
        page_title="Speech Perception Study",
        page_icon="🎧",
        layout="wide",
        initial_sidebar_state="collapsed",
    )

    # Hide sidebar entirely
    st.markdown("""
        <style>
        [data-testid="stSidebar"] { display: none; }
        .block-container { max-width: 1400px; padding-top: 2rem; margin: 0 auto; }
        </style>
    """, unsafe_allow_html=True)

    init_session()

    # Scroll back to top whenever the user navigates to a new page or new stimulus.
    nav_state = (
        st.session_state.page,
        st.session_state.stimulus_index,
        st.session_state.practice_index,
    )
    if st.session_state.get("_last_nav_state") != nav_state:
        st.session_state._last_nav_state = nav_state
        st.components.v1.html(
            """
            <script>
              function scrollAllToTop() {
                const doc = window.parent.document;
                const candidates = [
                  doc.querySelector('section.main'),
                  doc.querySelector('.main'),
                  doc.querySelector('[data-testid="stAppViewContainer"]'),
                  doc.querySelector('[data-testid="stMain"]'),
                  doc.querySelector('section[data-testid="stMain"]'),
                  doc.scrollingElement,
                  doc.documentElement,
                  doc.body,
                  window.parent,
                ];
                for (const t of candidates) {
                  if (!t) continue;
                  try { t.scrollTop = 0; } catch (e) {}
                  try { if (t.scrollTo) t.scrollTo(0, 0); } catch (e) {}
                }
              }
              // Retry several times to outrun Streamlit's late layout adjustments.
              scrollAllToTop();
              [0, 50, 150, 350, 700].forEach(d => setTimeout(scrollAllToTop, d));
            </script>
            """,
            height=0,
            width=0,
        )

    page = st.session_state.page
    if page == "welcome":          page_welcome()
    elif page == "demographics":   page_demographics()
    elif page == "instructions":   page_instructions()
    elif page == "practice":       page_practice()
    elif page == "block_intro":    page_block_intro()
    elif page == "rating":         page_rating()
    elif page == "break":          page_break()
    elif page == "thank_you":      page_thank_you()
    else:
        st.error(f"Unknown page: {page}")


if __name__ == "__main__":
    main()